name: Oppiabot

on:
  merge_group:
    types: [checks_requested]
  issues:
    types:
      - labeled
  pull_request_target:
    branches:
      - develop
      - release-*
permissions: read-all

jobs:
  oppiabot:
    name: Verify CLA
    runs-on: ubuntu-22.04
    permissions:
      issues: write          
      pull-requests: write   
      checks: write 
      statuses: write        
    steps:
      - name: Checkout repository so that local actions can be used
        uses: actions/checkout@v4
      - name: Merge develop branch into the current branch
        uses: ./.github/actions/merge
      - name: Github Actions from Oppiabot
        uses: oppia/oppiabot@1.4.0
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
        env:
          SHEETS_TOKEN: ${{ secrets.SHEETS_TOKEN }}
          SHEETS_CRED: ${{ secrets.SHEETS_CRED }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
